### ISSUE TITLE
Don't keep shooting downed zombies.

### ISSUE THREAD

**Issue by perkinslr** [pardeike/Zombieland#15]
With combat extended and ammo tracking turned on, colonists will waste a large amount of ammo on zombies which are currently down.  A way to selectively turn that off, especially for limited use weapons would be nice.

**Comment by pardeike** [comment]
This could be intended. Check if your “zombies self-heal” option is on, if not, this is a bug. If it IS on, the is the correct behaviour as they can stand up again if you don’t kill them.

**Comment by perkinslr** [comment]
Zombie self-heal is on, and I get that this is intended behaviour.  It's still a problem with limited-use weapons.  First, it isn't safe for the melee pawns to close in and finish off the zombies while their friends are shooting (this is a problem even without combat extended, but the unlimited ammo mitigates it some).  Second, while the zombie is down, it's harder to hit.  This means you spend more ammo than you would if you waited for it to get back up.  Third, targeting is slightly sticky.  There are lots of cases where the colonists continue to shoot at the downed zombie, while there are still plenty of rampaging zombies that should be higher priorities.  Fourth, you often don't care about killing the zombie.  If you are outside of your main zone, say grabbing cargo or escorting outsiders, the goal is simply to stop the zombie long enough to get past them safely.  Birdshot is the go-to load for this, as even with the fast healing, it will usually take an hour (game time) for the zombie to get back up, by which point you're long gone.  Unfortunately, birdshot is quite unlikely to kill the zombie, so your pawns will waste all their ammo on it if left unattended.  Fifth, continuing to shoot means needing to reload.  Combined with the noise from shooting attracting other zombies, the lower accuracy meaning you probably won't finish off the downed zombie before needing to reload, and the sticky targeting, this often turns into needing to run away mid-fight from an empty mag (or worse, running out of ammunition entirely).

All of these problems are especially bad in the early game.  The default scenario starts you with 40 rounds of revolver ammo, and 80 rounds of rifle ammo.  Until you get a comms console or a loading bench, you're probably not getting more.  Used to be doable, you only bother to kill zombies that are a problem, you finish off downed zombies with a knife or sword (while other pawns provide cover), if you have a good melee fighter, a proper sword and shield, and halfway decent armour, you take single zombies on in melee.  Now, you have to micro your pawns in combat, turn off fire at will, force targeting of each zombie until it goes down and then cancel the forced target.  Set the pawns to flee instead of fight, and hope you notice when someone is forced to flee.

Ideally, there'd be a gizmo on the action bar to select firing at downed zombies.  A default behaviour of not firing at zombies when using a weapon with limited ammo would also work (I've not tested doomsday rockets, but I suspect the pawns would waste the shot, which is a problem even without CE).  Failing that, a global option would probably suffice, as the old behaviour was liveable (you could always manually target the downed zombies if you didn't want to leave them).

**Comment by pardeike** [comment]
v1.11.2 hopefully fixes the shooting priorities
