### ISSUE TITLE
Incompatibility between Zombieland and Alpha animals

### ISSUE THREAD

**Issue by Valerate** [pardeike/Zombieland#16]
Crosspost from their Github, I'm not sure wich end the issue is easiest to fix

https://github.com/juanosarg/AlphaAnimals/issues/1

**Comment by pardeike** [comment]
I will try to make my postfix patch more defensive.

**Comment by pardeike** [comment]
https://github.com/pardeike/Zombieland/tree/SmoothZombies contains not only a new way to deliver faster performance, but even a possible fix for this issue. Feedback welcome.
