### ISSUE TITLE
Tanky Zombies with Combat extended getting 1 shot, Completely ignoring the tanky part

### ISSUE THREAD

**Issue by Valerate** [pardeike/Zombieland#17]
Hi

So I noticed that the tanky zombie just seemed to disappear, often after nothing more than a mad animal. After spawning one through console and shooting it with a single FMJ it just died. It seems like the whole tanky part of the zombie is nonfuctional and they die like a normal zombie

ModList; https://pastebin.com/JaxTzww1

Hugslib (its super long) https://gist.github.com/HugsLibRecordKeeper/75c6f4e97d7d143caba4d1d0108d15aa

Unsure which end to report this, I assume it has something to do with the comp patch but I have no idea what to do to fix it. I asume the tanky part is done through code rather than XML

**Comment by Valerate** [comment]
Well apparently loading it earlier fixed this, I'm sorry for wasting your time!

**Comment by Valerate** [comment]
I retract my statement, a tanky zombie was just 1shot from a headshot from a simple LMG

**Comment by pardeike** [comment]
Sorry, this isn’t the first time i need to fix things CE breaks and honestly, I am getting a bit tired of it.

**Comment by pardeike** [comment]
Fixed in the next release!
