### ISSUE TITLE
[Wishlist Suggestion] Option to "Save settings to local"

### ISSUE THREAD

**Issue by eksynn** [pardeike/Zombieland#19]
Could we have a "save settings to local" button as well? my internet is extremely slow, so uploading or downloading settings never work for me - it would also make it easier and faster to use my custom settings across new games as well

thanks in advance!

**Comment by pardeike** [comment]
That’s sort of already build in. You can set the default settings when you are at the start menu (not in a game). Go to the mod settings and it affects the defaults. Doesn’t give you a way to save multiple sets but at least you can define your favourite set.

**Comment by eksynn** [comment]
oh, i hadn't realised that lol - thanks
the "settings export to local" suggestion remains open then, in case you ever consider doing that xD but this should be good enough for me since i'm the only one who plays it ^^

pre-send edit:
i just realised why i asked for this - i wanted to grab the settings from my old game and apply it to the new one lol - is this at all possible, currently?

**Comment by pardeike** [comment]
If you want to copy the Zombieland settings from an old game to a new and you are not afraid of copying settings xml, you can start a new game with any ZL settings and save it. Then open the save file and the old save file and copy over the part where ZL saves its settings.
