### ISSUE TITLE
Zombies are immune to heated air

### ISSUE THREAD

**Issue by ramtinsoltani** [pardeike/Zombieland#20]
I have a maze set up as the only entrance to my base with an opened door. The temperature of the maze is usually around 1000 degrees celcius which would burn any raiders/pawns in a matter of seconds. However, when zombies are walking through the maze they won't die at all. I had two zombies walking in the maze for an hour and nothing happened. Is this property stripped out from the zombies?

**Comment by pardeike** [comment]
Yes, zombies don’t react to weather which in this case has the negative effect of making them immune to high temp. Not sure if I can fix this easily. 

I’ll keep this Issue open to remind me about it.

**Comment by pardeike** [comment]
Fixed in the next release - they will catch on fire and burn to death!
