### ISSUE TITLE
Pawn Freezing Potential Incomp with  Common Sense

### ISSUE THREAD

**Issue by SaintsWolf** [pardeike/Zombieland#23]
[Error code.txt](https://github.com/pardeike/Zombieland/files/3637366/Error.code.txt)
This is what she sent me. Probably with more unrelated Errors
[The Retreat back up.rws.txt](https://github.com/pardeike/Zombieland/files/3637413/The.Retreat.back.up.rws.txt)
Save file now in here as well as mod list 
https://steamcommunity.com/sharedfiles/filedetails/?id=1740592188

**Comment by pardeike** [comment]
That is some weird error text file. Is there anything else that is more like a normal stack trace? I saw the video but the colonist related to the error is outside the view and I can hardly read the red text - even in 720p

So many mods and an error after almost 3 hours playing isn’t making me confident that I can actually use this to find a bug/problem.

**Comment by pardeike** [comment]
Also: a bit later, she drafts the stuck colonist and you can see in the video that she had avoidance turned off - that makes even less sense as it basically shortcuts all the extra logic. I am beginning to think that this isn’t Zombieland related.

**Comment by SaintsWolf** [comment]
I'm sorry but i dont know what you mean by a stack trace My knowledge on these things is so limited. and if you go to the the 2 hour 49 minute mark. you can see the colonist in the top left of the screen in which she will eventually unpause. and it may not be Zombieland related but atm we can (paper and i) only assume so as this was working fine (as you saw the otherday) and the only mod update she had was zombie land. but upon removing "Common Sense" the issue has since been resolved. Albeit we were unable to test for much longer (only about an hour or so) after removing common sense.

**Comment by pardeike** [comment]
No problem. I got another report and hopefully a save file where the problem occurs just after load and that will help me solve this. If its Zombielands fault I will make sure to fix this asap.

**Comment by pardeike** [comment]
Fixed
