### ISSUE TITLE
(Discord Preview v2.2) error when someone turns into a powerful zombie

### ISSUE THREAD

**Issue by pastorismylord** [pardeike/Zombieland#29]
[zombieland rt 1.zip](https://github.com/pardeike/Zombieland/files/6588854/zombieland.rt.1.zip)

when someone turns into a powerful zombie this error triggers:

https://gist.github.com/320cd5977c439cc021626b81f3dfbc07

Savefile attached ready to trigger the issue.

**Comment by pardeike** [comment]
Found and fixed in upcoming release. It was a faction-less guy turning into a zombie and the convert routine failed on the null faction
