### ISSUE TITLE
Zombies ignore raiders, raiders don't ignore zombies.

### ISSUE THREAD

**Issue by Mehni** [pardeike/Zombieland#3]
Bit of an oddity with setting Zombies to only rage against colonists: Raiders will attack them, often ignoring colonists.  Zombies will continue ignoring raiders (while getting killed), until the raiders finally give up and leave.

Not sure if this is as intended, but it seems weird to me. 

Possible solutions:
- Make non-player factions friendly with the zombiefaction. Zombies and raiders will now ignore mutually ignore each other, much like Traders and Tribals.
- Make zombies always fight back when engaged in melee.
- Some other clever Brrainz solution.
- Leave as is.

**Comment by pardeike** [comment]
This is rather tricky. I discussed this on discord and it seems that there is no easy solution to this problem.

**Comment by SametAhmetSahin** [comment]
Isn't there a setting of that in the Zombieland settings? Like "All Creatures, Human-Like Creatures and Colonists"?

**Comment by pardeike** [comment]
Maybe I misunderstand this request, Mehni. Do you want raiders to ignore zombies if zombies are set to only attack colonists? That specific case is possible to patch. I think I could add a checkbox to the setting that, if you choose "only colonists" you can choose "raiders attack zombies anyway". I think that having such an option is favourable since I think some players like the way it works right now.

**Comment by Mehni** [comment]
> Do you want raiders to ignore zombies if zombies are set to only attack colonists?

Yes, precisely. Raiders shouldn't attack zombies if zombies don't attack them: 1-way-hostilities in RimWorld are rare.

My expectations of Hostile To All Human-Likes and Hostile To Colonists only: 

If I select Zombies to be hostile to all humans, I am mostly stuck in my base, I have to be self-sufficient. Traders die before reaching my base, raiders die before reaching my base. That's awesome if you want a game that heavily focuses on Zombies.

If I select Zombies to be hostile to my colonists only, I expect a more or less normal game of RimWorld, with the normal raids and traders being able to move freely (zombie inoculation? idunno) and on top of that the constant threat from Zombies.

> I think that having such an option is favourable since I think some players like the way it works right now.

You're the best.

**Comment by pardeike** [comment]
Fixed in the latest release!
