### ISSUE TITLE
'Color' does not contain a definition for 'RGBMultiplied'

### ISSUE THREAD

**Issue by cseelhoff** [pardeike/Zombieland#30]
https://github.com/pardeike/Zombieland/blob/9b044a4df4475f41441d61fad5b12657d26cd7c4/Source/Dialogs.cs#L95

This seems to prevent compiling master branch.

Is this line needed? It seems to be overwritten by line 99 perhaps?

**Comment by pardeike** [comment]
That seemed to be related of having an older version of Krafs. After updating it, I get the same error. I replaced the line with

```cs
var color2 = color;
color2.r *= 0.25f;
color2.g *= 0.25f;
color2.b *= 0.25f;
color2.a *= 0.2f;
GUI.color = color2;
```

**Comment by pardeike** [comment]
Fixed in master
