### ISSUE TITLE
Zombieland update bug

### ISSUE THREAD

**Issue by rex6564** [pardeike/Zombieland#34]
Hey thank you for the great mod I just want to say though I found a problem with the update if you do not have sos2 it throws the error rimworld failed to find rimworld.biome def named outer space biome. After testing rimworld with out Zombieland error stopped. just thought you would like to know thank you.

**Comment by pardeike** [comment]
It's a cosmetic bug, but one that potentically can slow down the game. I'll make a quick update, thanks

**Comment by pardeike** [comment]
I just fixed it and to verify I loaded the game with the current release and could not find such an error. Can you post the exact error with the full stacktrace from the Player.log?

**Comment by pardeike** [comment]
Fixed in the newly released 2.9.1

**Comment by rex6564** [comment]
Thank you so much have a fantastic day!
