### ISSUE TITLE
Zombies destroy weapons

### ISSUE THREAD

**Issue by pardeike** [pardeike/Zombieland#35]
Whenever a pawn is attacked in melee by a zombie, their ranged weapon disappears. It is not dropped, it just completely disappears. no error logs are shown in the debug console.

-- submitted by fabian.valk@gmail.com

**Comment by ffftian** [comment]
yes，yes，This is the problem I encountered. I hope it can be solved!

**Comment by pardeike** [comment]
Bug in CE and is going to be fixed in the next release
