### ISSUE TITLE
Cannot click on or highlight zombies

### ISSUE THREAD

**Issue by PonkyVT** [pardeike/Zombieland#43]
As title says, I cannot click on or highlight zombies to see their health

**Comment by pardeike** [comment]
This is documented in the last sentence in the first paragraph that has the headline "About":

*This Mod features custom controlled Zombies with simulated instincts. Most default RimWorld functions have been disabled on them to allow for a smooth game play experience. Therefore, you cannot select or harvest them.*

Zombies do have a health bar that is shown on mouse over. It contains overall health and conciousness.
