### ISSUE TITLE
"Zombie Infection" brain hediff prevents harvesting the brain post-mortem.

### ISSUE THREAD

**Issue by Fokson** [pardeike/Zombieland#47]
I'm using the Harvest Organs Post-Mortem mod as well as the "Brain in a Jar" mod to harvest pawn brains.  When an organ has any hediff whatsoever it becomes ineligible for harvesting, so despite there being nothing wrong with the brain technically it can never be harvested since the mod applies the 'zombie infection' hediff to the brain immediately on death.

I've circumvented this issue for now by disabling corpses from rising as zombies but I do like the threat of unchecked corpses coming back to "life".  Would it be possible to change that hediff to apply to the whole body instead of the brain?

**Comment by pardeike** [comment]
No, the effect being that if the brain is destroyed (for example by “double tapping” or by any other means then they won’t become zombies again

**Comment by Fokson** [comment]
I understand the idea behind it, but nevertheless it'd be nice to see it as an option for the sake of compatibility ( maybe have it affect that 'head' as opposed to the brain so the double tapping still works as intended but doesn't prevent the brain from being harvested ).  If not though that's fine, I'll just have to leave the setting of corpses becoming zombies off.  Thanks anyway!

**Comment by pardeike** [comment]
Sorry but if I rebuild my mods for the sake of compatibility with other mods I would be busy 24/7. 

When I see a major incompatibility with something that most users want or expect I see if a tweak on my side could fix it and it usually does. 

On the other hand if I get requests from players to change a core part of my code for a rather specific issue I have to be realistic and decline it. With so many mods out there, you can’t imagine the number of requests I get every week.
