### ISSUE TITLE
Colonists do not move 

### ISSUE THREAD

**Issue by MNG-cataclysm** [pardeike/Zombieland#50]
Game version: 1.3.3389 (64 bit)

Mod list (by load order): Harmony, Core, Royalty, Ideology, Zombieland 

When starting a new colony, the initial arrivals refuse to move from the square their landing pods crashed at, interact with anything, or be drafted. When given specified orders, they do not move, although they display a pathing line and their activity is specified on their UI screen. Everything else moves normally, including animals. 

Additionally, I receive an error message that the map could not load when attempting to start the game again after saving and exiting. 

I disabled Zombieland and ran the game with Harmony, download from the GitHub page, and had no issues. 

I am not using Steam to run the game, and I downloaded Zombieland from the Rimworld Base page.

**Comment by pardeike** [comment]
Can you share a save game file that exhibits with us?

**Comment by MNG-cataclysm** [comment]
[Failure Save.zip](https://github.com/pardeike/Zombieland/files/9059749/Failure.Save.zip)

@pardeike Here is the save file in question.

**Comment by pardeike** [comment]
Works fine for me: https://www.youtube.com/watch?v=nPHcvSf2Xy8

**Comment by pardeike** [comment]
I would really like you to never download mods from unofficial sources. Only trust either Steam or the official GitHub repository as advertised by the original author. In this case this repository. Simply download the zip of the latest release or master and put its unzipped folder into Mods.

**Comment by MNG-cataclysm** [comment]
> I would really like you to never download mods from unofficial sources. Only trust either Steam or the official GitHub repository as advertised by the original author. In this case this repository. Simply download the zip of the latest release or master and put its unzipped folder into Mods.

@pardeike  
Thank you for your help, I'll keep that advice in mind for the future.
