### ISSUE TITLE
Draftable friendly animals/creatures do not show command panel

### ISSUE THREAD

**Issue by Crockan** [pardeike/Zombieland#51]
When Zombieland is installed into the game, it seems that the command icons for animals/creatures that can be conscripted will disappear

For example, the robots that can be built in VFE Mechanoids, and the animals that can be drafted from VGE. It is not possible to give them commands, and shortcut keys does not respond.Right click still works though.

**Comment by pardeike** [comment]
Please provide a minimal replication game and upload the save file.

**Comment by Crockan** [comment]
[Game save file](https://drive.google.com/file/d/1yD0b6p1PFOQ7qpi3WanT1nDrLDjZOnIp/view?usp=sharing)

[Game Copy](https://drive.google.com/file/d/1TBlBvJdu9An_ytYXTRiiOq2fchxB_M8x/view?usp=sharing)

In the game "insectoid paragon 1" should be able to be drafted, but the reality does not

**Comment by pardeike** [comment]
I tried it and I cannot draft it. Then I removed Zombieland but I still could not draft the insectoid. I tried to add a fresh new one and I still could not draft one without ZL. Seems like this is unrelated to ZL.

**Comment by Crockan** [comment]
It appears that animals that already exist cannot be drafted by removing the ZL to restore their ability to be drafted
The problem seems to require you to make a new draftable animal from genomorpher in order for the other animals with problems to be draftable as well (maybe it's a refresh?)

Sorry I didn't elaborate this before, but you might want to create a new animal and test it again

**Comment by pardeike** [comment]
Hmm, cannot reproduce. This is without ZL:
https://i.imgur.com/sCzaloo.jpeg

**Comment by pardeike** [comment]
I tried to create a whole new game with your mods but without ZL. Created a new animal via dev tools, then used dev tools to tame it and train it. Still cannot draft it.

**Comment by Crockan** [comment]
hmmmmm...... weird, forget about the draft.
The main problem is that this menu doesn't appear at all with ZL, maybe the draft thing is a VGE problem, but all the other buttons have disappeared too
![image](https://user-images.githubusercontent.com/45941794/181724752-ddc3ef37-8a38-4b9c-9dd3-f113eb6ef232.png)
When I was having ZL these buttons would not appear at all, can you try this to see if it can be reproduced?

**Comment by pardeike** [comment]
Your save game:
https://www.youtube.com/watch?v=b6UapPg1bns

**Comment by Crockan** [comment]
Well ...... I don't know what to say, I just tested it once myself and found that the problem is indeed no longer present. Sorry if I disturbed or bothered you.

**Comment by Crockan** [comment]
I have tested another mod, mechanoid, that is having issues too.
I managed to create a stable and reproducible ( presumably ) save file, please check it again if you are not bothered.

[- Game copy & save file](https://drive.google.com/file/d/1m4zkZRlYo58bjogrh1Ds4XhVd9hlfk9t/view?usp=sharing) (save file in the folder)
[- Demo video with and without ZL](https://drive.google.com/file/d/18OPlYgYTd9Hb0xmnOo9mJET3oDFxaMLx/view?usp=sharing)
