### ISSUE TITLE
Problem with the gui due to incompatible mods

### ISSUE THREAD

**Issue by LaytonBaccea** [pardeike/Zombieland#55]
When i install all of the 25 mods and play a save, it works fine, but when i add zombieland and play the same save afterwards it doesn't, when the bug happens the whole gui is gone and a grey ish paint covers the whole screen, the game is still fully interactable and i can see my pawns move around, and the gui and grey ish paint disappears when i click on the gui or press escape, but when i close the gui the bug starts all over again.
However it seems that i can fix it by just creating a copy of my current save in the folder, the bug is gone

**Comment by pardeike** [comment]
You have some sort of mod conflict. Without more details from the player log it’s hard to tell.

**Comment by LaytonBaccea** [comment]
I will try to recreate it ;)
