### ISSUE TITLE
Zombieland creates insane amount of errors in player and player-prev documents

### ISSUE THREAD

**Issue by LaytonBaccea** [pardeike/Zombieland#56]
It seems that zombieland mod are creating insanely many players as the zombies spawns.... i got a message from windows that my windows harddisc is full and that i needed to clear space immediately. Is the mod supposed to create ''players'' when every zombie spawns?, i had above 500 zombies on the map tile, and the other map tile.
Anyway i had to disable the mod so the zombies disappeared, and i deleted the player and player-prev dokuments.

![Bug](https://user-images.githubusercontent.com/50519235/185233542-966c10a5-13f6-4c16-a355-120abf7f4c75.png)

**Comment by pardeike** [comment]
I was first confused by what you mean with “players” but the file that got so big for you is the game file where all the potential errors and other things are logged. I have no idea what’s in it so I can’t help you without more details. 

Most likely the same text in it is repeated over and over again so if you can find and post just that you skip the hassle of uploading the whole.

**Comment by LaytonBaccea** [comment]
I have tried to open them but it only loaded 8% after 10 minutes has gone.... 
i will try to recreate the bug so i can see what error happens

**Comment by LaytonBaccea** [comment]
I think i got the right ones?, i took a look at it myself, and it seems that player-prev creates a lot of nulls of some sort.... not very good at this programming thing :P .
Just to clearify, the player named Tylo is a race from Twilek from starwars race mod

[Player-prev.log](https://github.com/pardeike/Zombieland/files/9371682/Player-prev.log)
![Tylo trying to hit electric zombie (2)](https://user-images.githubusercontent.com/50519235/185343642-f5392224-e43b-4897-905c-d7770d04d264.png)
![Tylo trying to hit electric zombie](https://user-images.githubusercontent.com/50519235/185343683-cea93c0c-2043-4a50-8395-20ad301edf74.png)

**Comment by pardeike** [comment]
That’s not an error from Zombieland. It’s some other pawn getting scheduled a lot of jobs on zombies. This seems to be a mod conflict and you need to sort this out yourself by going through your mods and reducing them until it works
