### ISSUE TITLE
Tanky zombie does insane amount of dmg

### ISSUE THREAD

**Issue by LaytonBaccea** [pardeike/Zombieland#57]
I am in doubt if this is a bug or intended about the tanky zombie, when i made a pawn got meele hit the zombie, it killed my pawn in one hit, the damge indicator under health; Torso; 0/48: zombie bite teeth: 256.4... is it intended that you should absolutely not engage with a tanky zombie in a meele fight, or is it a bug?

**Comment by pardeike** [comment]
Intented. They are insanely powerful to knock down walls. Don't melee them.
