### ISSUE TITLE
Issue: Uninfected dead pawns become strong zombies anyway

### ISSUE THREAD

**Issue by LaytonBaccea** [pardeike/Zombieland#58]
I know that this is meant to be, but it would be lovely if you made an option to turn it off, it feels very unrealistic when an uninfected pawn die, turns into a strong zombie... no matter what... unrealistic

**Comment by pardeike** [comment]
There is an option to turn it off already, set the time it takes to "off"

**Comment by LaytonBaccea** [comment]
Sorry mate.... but it still happens, i banished a pawn because he destroyed 50 components, then he froze to death outside and turned into a strong zombie after a while

**Comment by pardeike** [comment]
Doesn't do that for me. As you can see, that pawn died without becoming a
zombie.
/Andreas

**Comment by LaytonBaccea** [comment]
Okay, so it can't be fixed? :)

**Comment by pardeike** [comment]
Can’t fix a thing that isn’t broken.

**Comment by LaytonBaccea** [comment]
Well something is not right, because your zombieland mod plants an infection in their brains even though they haven't been bitten or hurt by zombies, even though i have turned that setting off that you mentioned to me

**Comment by pardeike** [comment]
Not sure what you expect from me but I cannot fix “something”

**Comment by LaytonBaccea** [comment]
You could make a feature in the settings that makes us able to turn on/off that will make all pawns in the game only get infected through zombies and not when they die without having any damage from zombies?  :)

**Comment by pardeike** [comment]
Yeah, that’s the screenshot I attached earlier. It shows precisely that setting.

**Comment by LaytonBaccea** [comment]
Oh sorry.... i can't find the screenshot, i am not very familiar with github... same as reddit,  could you tell me where i can find it

**Comment by pardeike** [comment]
![image](https://user-images.githubusercontent.com/853584/187440176-504dcbc8-291e-4806-be05-642edac74f5d.png)

Drag this to the left and it will say "Off". For more information, check out [this tutorial](https://www.youtube.com/watch?v=e2Kbt9xyTno)

**Comment by LaytonBaccea** [comment]
Huh....  thanks mate!, i don't know if it is just me, but it is a bit confusing to turn it off when there's no sign of it saying ''turn off'' or something similar
