### ISSUE TITLE
Support RimWorld version 1.4

### ISSUE THREAD

**Issue by JonnMsft** [pardeike/Zombieland#61]
RimWorld just came out with the new Biotech DLC and upgraded the version to 1.4. Zomebieland is still marked as compatible only with 1.3. (Love this mod by the way!)

**Comment by pardeike** [comment]
I am currently testing a 1.4 version. Join my discord and the #zombieland channel and download the pre-release

**Comment by pardeike** [comment]
https://discord.gg/MTpqYcPQd3
