### ISSUE TITLE
Improve extraction and double-tap with drafted pawns

### ISSUE THREAD

**Issue by JonnMsft** [pardeike/Zombieland#62]
Extraction and double-tap require more manual fiddling than is necessary. Here are two suggestions:

- Drafted pawns should ignore their assigned zone, and should be able to extract or double-tap regardless of whether the corpse is in their assigned zone.
- Drafted pawns should ignore their work assignments, and should be able to extract or double-tap regardless of whether they are assigned to Doctor or Hunt.

Definitely this should apply if the pawn is explicitly commanded to extract or double-tap, not sure whether this applies to extract/double-tap by default.

BTW I have done a long writeup on Surviving Zombieland, but I'm not sure where to post it. Registration is disabled on the Ludeon Studios forum.

**Comment by pardeike** [comment]
Use Achtung for this. It allows you to do all kind of work outside of allowed zones or forbidden things or work assignments when a colonist is drafted.

**Comment by pardeike** [comment]
All communication is done in my discord. Ludeon forums are not really a thing anymore: https://discord.gg/MTpqYcPQd3
