### ISSUE TITLE
Albino zombies being annoying as usual...

### ISSUE THREAD

**Issue by supremecmdr** [pardeike/Zombieland#65]
Well, the albinos try to annoy me as much as they can,

so for one they keep opening doors locked with the Locks mod by Avius https://steamcommunity.com/sharedfiles/filedetails/?id=1157085076

and as a side note, I got angry for a moment for the multipleth failure of my part and set 100 heat waves on the map to watch everything living burn alive.. but guess the albinos are heatproof as well, all the other zombies or what not got incinerated but not the albinos..

**Comment by pardeike** [comment]
Albinos should behave the same as every other zombie. And no, I don't support arbitrary mods that conflict with the way Zombieland is designed.

**Comment by supremecmdr** [comment]
Ok, thanks for the awesome fun by the way, will just find ways around this unlocking thing. Take care.
