### ISSUE TITLE
Zombieland Unable to use

### ISSUE THREAD

**Issue by kiauio** [pardeike/Zombieland#66]
I only installed the body with the front, but it still does not work, while I was able to use it two days ago, I verified the integrity of the game, but also replayed the mod, but still can not solve the problem
![20230111220833_1](https://user-images.githubusercontent.com/113630423/211827549-257ea797-523b-4ae0-8280-240a66425521.jpg)
Here are some of the red letters：
Error in static constructor of ZombieLand.Constants: System.TypeInitializationException: The type initializer for 'ZombieLand.Constants' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at ZombieLand.Constants..cctor () [0x011b2] in <fe12e6adef8540519ffeb9572c2847f5>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(intptr)
  at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (System.RuntimeTypeHandle type) [0x0002a] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Verse.StaticConstructorOnStartupUtility.CallAll () [0x00025] in <3126aca1aad041dcbdeda807cfe004bf>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.StaticConstructorOnStartupUtility:CallAll ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_5 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
Verse.Root:Update ()
Verse.Root_Entry:Update ()

**Comment by pardeike** [comment]
What version of ZL and RW are you using? Is your mod order correct?
Without more information I would need to close this issue

**Comment by pardeike** [comment]
And... closed
