### ISSUE TITLE
An unintended way to erase contamination from the map

### ISSUE THREAD

**Issue by Ankaleri** [pardeike/Zombieland#75]
By request, I'm copying my bug reports from Discord to Github.
I found that under very specific circumstances you can get a completely decontaminated map with contamination setting enabled. This bug does not produce any error, the initial contamination just disappears from the map without a trace.
The easiest way to reproduce:
1. Run dev quicktest, then immediately quit to main menu.
2. Start a new colony with "Dev quicktest'. Create a save with it.
3. Load your newly created save. Poof - a perfectly sterile map without any sign of contamination.
Here's the log just in case: https://gist.github.com/HugsLibRecordKeeper/9f5a3661085b554ff37d550435e52823

**Comment by pardeike** [comment]
fixed in next release
