### ISSUE TITLE
Lots of errors appear when you try to open a zombie's health tab

### ISSUE THREAD

**Issue by Ankaleri** [pardeike/Zombieland#77]
By request, I'm copying my bug reports from Discord to Github.
if I select a pawn turned into zombie, open their info window then go to Health tab, my debug log immediately gets flooded with errors.
https://gist.github.com/HugsLibRecordKeeper/1e84a4de70be7aedae3c02ca9915c3f3

**Comment by pardeike** [comment]
Fixed in next release
