### ISSUE TITLE
Zombies not spawning in city buildings (Rimcity)

### ISSUE THREAD

**Issue by Duxtorm** [pardeike/Zombieland#78]
With the "When it is dark" option selection under "When do zombies appear?", I found that zombies weren't spawning in uncharted cells within Rimcity buildings.. I'm wondering if I've done something wrong.

My goal is to recreate the setup in ambiguousamphibian's video.
https://www.youtube.com/watch?v=Yc9vuBVXsMc

**Comment by pardeike** [comment]
Zombies spawn in buildings as soon as the room is discovered. The chance for that is the same setting as the "visitors/enemies enter map preinfected"

/Andreas Pardeike

**Comment by Duxtorm** [comment]
Oh, I find that a bit confusing. Under "Zombie event" where you can change what percentage of "arriving groups are infected"; I'd assume that meant that the random travellers and raiders that come onto the map would have that set chance of already being infected, but I don't understand the connection of that also controlling how likely it is for zombies to appear when you discover a dark room.

So, to clarify.. if I set "arriving groups are infected" to 50%, does that mean that 50% of the people that arrive on the map will be infected as well as half of all rooms I search will contain zombies?

**Comment by pardeike** [comment]
Yes, that’s correct. I was lazy and did not create a new setting for the room feature.

**Comment by Duxtorm** [comment]
🫡
Thank you for the clarity, and thank you for your replies, that was all I was confused about.
